cf:
  sslValidationSkipped: false
  connectionPoolSize: 250
  connectionTimeout: PT10M

spring:
  application:
    name: cf-archivist
  codec:
    max-in-memory-size: 512000000
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.hooverRegistry.credentials.uri:http://localhost:8761}/eureka/

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron:
  # each :30 on the hour
  collection: "0 30 * * * *"
  # at 5:30am on Mondays weekly
  execution: "0 30 5 * * MON"

management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,loggers,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

---
spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    discovery:
      enabled: true

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

