cf:
  sslValidationSkipped: false
  connectionPoolSize: 250
  connectionTimeout: PT10M

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron:
  # each :30 on the hour
  collection: "0 30 * * * *"
  # at 5:30am on Mondays weekly
  execution: "0 30 5 * * MON"

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.hooverRegistry.credentials.uri:http://localhost:8761}/eureka/

logging:
  level:
    io.r2dbc.h2.H2Connection: ERROR

management:
  info:
    build:
      enabled: true
    dependencies:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    sbom:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,loggers,metrics,prometheus
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: cf-archivist
  codec:
    max-in-memory-size: 512000000
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:pool:h2:mem:///cf-archivist?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true
    name: cf-archivist
    username: sa
    password: 
  ## Disable org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
  ## It curently interferes with startup login in Cloud Foundry operational context when either a MySQL or Postgres service instance is bound to application
  sql:
    init:
      enabled: false

# Java Mail
# Reset the values for spring.mail.username, spring.mail.password
# Configuration below is set up to work w/ a Gmail account
# @see http://www.baeldung.com/spring-email

  mail:
    host: smtp.gmail.com
    port: 587
    username: replace_me
    password: replace_me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# SendGrid API key (alternative to username/password).
  sendgrid:
    api-key: replace_me

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.github.appreciated.apexcharts

---
spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    discovery:
      enabled: true

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

